email:
  fromEmail: algemeen@wirelab.nl
  fromName: Wirecraft
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  9b582c0b-1028-45a9-ac51-1e9e2c8c47bb:
    name: Common
siteGroups:
  d2f7a020-49cd-4739-a66a-416188ba2f5d:
    name: Wirecraft
sites:
  1b1b9004-82c0-41dc-998d-a3d9cd21ac83:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: Wirecraft
    primary: true
    siteGroup: d2f7a020-49cd-4739-a66a-416188ba2f5d
    sortOrder: 1
system:
  edition: solo
  name: Wirecraft
  live: true
  schemaVersion: 3.3.3
  timeZone: America/Los_Angeles
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
