dateModified: 1615195292
email:
  fromEmail: algemeen@wirelab.nl
  fromName: Wirecraft
  transportType: craft\mail\transportadapters\Sendmail
system:
  edition: solo
  live: true
  name: Wirecraft
  schemaVersion: 3.6.6
  timeZone: Europe/Amsterdam
users:
  allowPublicRegistration: true
  defaultGroup: ''
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
  suspendByDefault: false
